from pydantic import BaseSettings


class Settings(BaseSettings):
    """
    Settings for the web application. Values are overridden with a
    configuration file "isb_web_config.env", normally located in
    the root folder of the web application startup.
    """

    logging_config: str = "logging.conf"

    # SQLAlchemy database URL string
    # e.g.: postgresql+psycopg2://DBUSER:DBPASS@localhost/isb_1
    database_url: str = "UNSET"

    # The Solr service URL, must end in "/"
    # e.g. http://localhost:8983/solr/isb_core_records/
    solr_url: str = "UNSET"

    # OAuth client id, generated by OAuth provider
    client_id: str = ""

    # OAuth client secret, generated by OAuth provider
    client_secret: str = ""

    # Set this to a random string, used for cookie obfuscation
    cookie_secret: str = "some-random-string"

    # The OAuth authorization endpoint
    authorize_endpoint: str = "https://github.com/login/oauth/authorize"

    # The OAuth endpoint for getting an access token
    access_token_endpoint: str = "https://github.com/login/oauth/access_token"

    # OAuth redirect URL. This must be exactly the same as the address
    # registered with the OAuth provider
    oauth_redirect_url: str = "https://mars.cyverse.org/githubauth"

    # Origins that are allowed to interact with the OAuth service
    # This is used to block authentication requests from unexpected
    # origins. Each entry is a python regular expression and the
    # request Origin must match one to use the OAuth flow.
    oauth_allowed_origins: list = [
        r"https://isamplesorg\.github\.io/",
        r"https://mars\.cyverse\.org/",
        r"https://(.*\.)?isample\.xyz/",
        r"https?://localhost(:\d{2,5})/",
    ]

    thing_url_path: str = "thing"

    stac_item_url_path: str = "stac_item"

    stac_collection_url_path: str = "stac_collection"

    # The URL to the analytics API
    analytics_url: str = "UNSET"

    # The domain to record analytics events for, needs to be configured as a site in plausible.io
    analytics_domain: str = "UNSET"

    class Config:
        env_file = "isb_web_config.env"
